In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df2=pd.read_csv(r'/content/phone search (1).csv', sep=',',encoding='utf-8')
df2

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"Gimbal Stabilizer for Smartphone, 3-Axis Phone...",$99.99,NaN,USD,4.7,8,1,$99.99,False,False,True,NaN,False,NaN,"FREE delivery Thu, Sep 26",False,NaN,NaN,Save 50% with coupon
336,B0CHB24KQJ,[True Military-Grade] Car Phone Holder【2024 St...,$39.99,$45.99,USD,4.4,2589,1,$39.99,False,False,True,NaN,False,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
337,B01LXOPZ4W,Wall Mount Cell Phone Charging Shelf | Multi-D...,$273.00,NaN,USD,4.1,45,1,$273.00,False,False,False,NaN,False,NaN,FREE delivery Sep 25 - 30,False,NaN,NaN,NaN
338,B0CXPJK7F7,"Sensyne 92&quot; Cell Phone Tripod, Selfie Sti...",$29.99,NaN,USD,4.6,29066,1,$29.99,True,False,True,NaN,False,300+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN
339,B0CQ237PFS,Portable Charger 33800mAh USB C Power Bank wit...,$45.95,$69.95,USD,4.4,672,1,$45.95,False,False,True,NaN,False,3K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,Save 20% with coupon

In [3]:
df=df2.copy()

In [4]:
df.describe()

,product_star_rating,product_num_ratings,product_num_offers,unit_count
count,337.000000,340.000000,340.000000,4.000000
mean,4.087537,2744.050000,8.426471,3.500000
std,0.383544,7331.816833,10.798389,1.732051
min,1.600000,0.000000,1.000000,2.000000
25%,3.900000,135.250000,1.750000,2.000000
50%,4.100000,503.500000,4.000000,3.500000
75%,4.300000,1874.250000,11.000000,5.000000
max,5.000000,64977.000000,83.000000,5.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 315 entries, 0 to 339
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         315 non-null    object
 1   product_title                315 non-null    object
 2   product_price                315 non-null    float64
 3   product_original_price       137 non-null    float64
 4   product_star_rating          315 non-null    float64
 5   product_num_ratings          315 non-null    int64
 6   product_num_offers           315 non-null    int64
 7   product_minimum_offer_price  315 non-null    float64
 8   is_best_seller               315 non-null    bool
 9   is_amazon_choice             315 non-null    bool
 10  is_prime                     315 non-null    bool
 11  climate_pledge_friendly      315 non-null    bool
 12  sales_volume                 296 non-null    object
 13  has_variations               315 non-null    bool
 14  sales_volume_clean           270 non-null    float64
 15  has_discounts                315 non-null    bool
dtypes: bool(6), float64(5), int64(2), object(3)
memory usage: 28.9+ KB

In [6]:
df=df.drop(columns=['unit_price','unit_count','coupon_text','product_availability'])

In [7]:
df[0:18]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False
5,B0BZG14KFJ,Panasonic Cordless Phone with Answering Machin...,$49.99,$59.99,USD,4.4,3843,3,$25.19,False,True,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24",False
6,B0C2SWQBMB,Motorola Moto G 5G | 2023 | Unlocked | Made fo...,$149.99,$249.99,USD,4.2,2637,8,$100.72,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
7,B0CTD47P22,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$149.50,$158.00,USD,4.2,253,9,$146.50,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
8,B0CSB14R7J,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$139.99,NaN,USD,4.3,573,15,$136.62,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
9,B0CHK6LWKZ,TracFone | Samsung Galaxy A03s | Locked | 32GB...,$59.99,NaN,USD,4.0,258,4,$50.48,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
10,B0C5BMB1WB,Motorola One Ace | 2021 | 2-Day Battery | Unlo...,$89.00,NaN,USD,4.0,204,10,$85.44,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
11,B0CRVWPWKP,Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM...,$195.00,NaN,USD,4.0,259,15,$164.50,False,False,True,False,400+ bought in past month,"FREE delivery Wed, Sep 25",True
12,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.0,610,2,$154.00,False,False,True,True,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
13,B0C22BRGLG,OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...,$249.99,$299.99,USD,4.3,963,5,$209.28,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
14,B09NZQJRN7,"VTech DECT 6.0 Cordless Phone - Blue Display, ...",$18.45,NaN,USD,4.3,9096,2,$13.84,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False
15,B09LKXHWCF,"Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...",$355.81,$415.00,USD,4.1,4265,20,$303.99,False,False,False,True,500+ bought in past month,"FREE delivery Tomorrow, Sep 20",True
16,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
17,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 3 left in stock...",False

In [8]:
df[df.duplicated(subset=['product_title','product_price','asin'], keep=False)]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
5,B0BZG14KFJ,Panasonic Cordless Phone with Answering Machin...,$49.99,$59.99,USD,4.4,3843,3,$25.19,False,True,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24",False
6,B0C2SWQBMB,Motorola Moto G 5G | 2023 | Unlocked | Made fo...,$149.99,$249.99,USD,4.2,2637,8,$100.72,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
7,B0CTD47P22,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$149.50,$158.00,USD,4.2,253,9,$146.50,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
8,B0CSB14R7J,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$139.99,NaN,USD,4.3,573,15,$136.62,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
9,B0CHK6LWKZ,TracFone | Samsung Galaxy A03s | Locked | 32GB...,$59.99,NaN,USD,4.0,258,4,$50.48,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
10,B0C5BMB1WB,Motorola One Ace | 2021 | 2-Day Battery | Unlo...,$89.00,NaN,USD,4.0,204,10,$85.44,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
12,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.0,610,2,$154.00,False,False,True,True,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
13,B0C22BRGLG,OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...,$249.99,$299.99,USD,4.3,963,5,$209.28,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
14,B09NZQJRN7,"VTech DECT 6.0 Cordless Phone - Blue Display, ...",$18.45,NaN,USD,4.3,9096,2,$13.84,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False
15,B09LKXHWCF,"Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...",$355.81,$415.00,USD,4.1,4265,20,$303.99,False,False,False,True,500+ bought in past month,"FREE delivery Tomorrow, Sep 20",True
16,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
17,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 3 left in stock...",False
18,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
19,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
20,B0BZG14KFJ,Panasonic Cordless Phone with Answering Machin...,$49.99,$59.99,USD,4.4,3843,3,$25.19,False,True,True,False,4K+ bought in past month,"FREE delivery Tue, Sep 24",False
21,B0C2SWQBMB,Motorola Moto G 5G | 2023 | Unlocked | Made fo...,$149.99,$249.99,USD,4.2,2637,8,$100.72,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
22,B0CTD47P22,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$149.50,$158.00,USD,4.2,253,9,$146.50,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
23,B0CSB14R7J,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,$139.99,NaN,USD,4.3,573,15,$136.62,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
24,B0CHK6LWKZ,TracFone | Samsung Galaxy A03s | Locked | 32GB...,$59.99,NaN,USD,4.0,258,4,$50.48,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
25,B0C5BMB1WB,Motorola One Ace | 2021 | 2-Day Battery | Unlo...,$89.00,NaN,USD,4.0,204,10,$85.44,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
27,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.0,610,2,$154.00,False,False,True,True,2K+ bought in past month,"FREE delivery Tue, Sep 24",True
28,B0C22BRGLG,OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...,$249.99,$299.99,USD,4.3,963,5,$209.28,False,False,True,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False
29,B09NZQJRN7,"VTech DECT 6.0 Cordless Phone - Blue Display, ...",$18.45,NaN,USD,4.3,9096,2,$13.84,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False
73,B09LKXHWCF,"Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...",$355.81,$415.00,USD,4.1,4265,20,$303.99,False,False,False,True,500+ bought in past month,"FREE delivery Tomorrow, Sep 20",True
97,B0CMDRFVTL,"SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartp...",$859.99,NaN,USD,4.4,424,2,$724.02,False,False,True,True,100+ bought in past month,"FREE delivery Tue, Sep 24",True
123,B0B8F1S1XG,AT&amp;T CL82219 DECT 6.0 2-Handset Cordless P...,$51.60,$65.95,USD,4.3,574,6,$27.67,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
126,B096YK3RN9,SAMSUNG Galaxy S21+ Plus G996U| Fully Unlocked...,$246.00,NaN,USD,4.0,1340,21,$187.00,False,False,False,True,100+ bought in past month,"FREE delivery Tomorrow, Sep 20 Only 5 left in ...",True
127,B0BTTQGVVW,"Cat S22 Flip (16GB) 2.8&quot; Touchscreen, And...",$64.94,NaN,USD,3.9,1492,9,$49.90,False,False,False,False,1K+ bought in past month,FREE delivery,False
128,B0BHHJV7W9,AT&amp;T CL82507 DECT 6.0 5-Handset Cordless P...,$117.77,NaN,USD,4.3,20608,4,$57.19,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
129,B0DB88HK1Z,Reno 11 Pro Unlocked Android Phone 6.7-inch HD...,$99.99,$119.99,USD,2.8,6,1,$99.99,False,False,True,False,List:,"FREE delivery Wed, Sep 25",True
131,B0B8F1S1XG,AT&amp;T CL82219 DECT 6.0 2-Handset Cordless P...,$51.60,$65.95,USD,4.3,574,6,$27.67,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
133,B096YK3RN9,SAMSUNG Galaxy S21+ Plus G996U| Fully Unlocked...,$246.00,NaN,USD,4.0,1340,21,$187.00,False,False,False,True,100+ bought in past month,"FREE delivery Tomorrow, Sep 20 Only 5 left in ...",True
134,B0DB88HK1Z,Reno 11 Pro Unlocked Android Phone 6.7-inch HD...,$99.99,$119.99,USD,2.8,6,1,$99.99,False,False,True,False,List:,"FREE delivery Wed, Sep 25",True
136,B0BHHJV7W9,AT&amp;T CL82507 DECT 6.0 5-Handset Cordless P...,$117.77,NaN,USD,4.3,20608,4,$57.19,False,False,True,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False
137,B0BTTQGVVW,"Cat S22 Flip (16GB) 2.8&quot; Touchscreen, And...",$64.94,NaN,USD,3.9,1492,9,$49.90,False,False,False,False,1K+ bought in past month,FREE delivery,False
212,B0CMDRFVTL,"SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartp...",$859.99,NaN,USD,4.4,424,1,$859.99,False,False,True,True,100+ bought in past month,"FREE delivery Tue, Sep 24",False
307,B0B4F4DH6H,"Panasonic Expandable Corded Phone System, Blue...",$114.28,$129.99,USD,4.2,539,2,$41.84,False,False,True,False,50+ bought in past month,"FREE delivery Tue, Sep 24",False
308,B0D6Z95D5K,Motorola Moto G04 XT2421-2 (Dual Sim) Factory ...,$119.99,NaN,USD,5.0,1,1,$119.99,False,False,True,False,NaN,"FREE delivery Wed, Sep 25",True
309,B0C9LPCS42,"Nothing Phone (2) - 512 GB + 12 GB Ram, Glyph ...",$689.99,NaN,USD,4.5,224,6,$640.28,False,False,False,False,More Buying Choices,FREE delivery,True
310,B0B4F4DH6H,"Panasonic Expandable Corded Phone System, Blue...",$114.28,$129.99,USD,4.2,539,2,$41.84,False,False,True,False,50+ bought in past month,"FREE delivery Tue, Sep 24",False
311,B0D6Z95D5K,Motorola Moto G04 XT2421-2 (Dual Sim) Factory ...,$119.99,NaN,USD,5.0,1,1,$119.99,False,False,True,False,NaN,"FREE delivery Wed, Sep 25",True
312,B0C9LPCS42,"Nothing Phone (2) - 512 GB + 12 GB Ram, Glyph ...",$689.99,NaN,USD,4.5,224,6,$640.28,False,False,False,False,More Buying Choices,FREE delivery,True

In [9]:
df=df.drop_duplicates(subset=['product_title','product_price','asin'], keep='first')

In [18]:
df.duplicated().sum()

np.int64(0)

In [13]:
df=df.drop_duplicates(subset=['product_title','asin'], keep='first')

In [19]:
df['product_price']=df['product_price'].str.replace('[^0-9.]','',regex=True).astype(float)

In [20]:
df['product_price']=df['product_price'].fillna(df['product_price'].median())

In [21]:
df['product_original_price']

0      $169.99
1           NaN
2       $99.99
3           NaN
4       $98.27
         ...
335         NaN
336     $45.99
337         NaN
338         NaN
339     $69.95
Name: product_original_price, Length: 315, dtype: object

In [22]:
df['product_title']=df['product_title'].str.lower().str.replace('\s+',' ',regex=True).str.strip()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-3694352936.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['product_title']=df['product_title'].str.lower().str.replace('\s+',' ',regex=True).str.strip()

In [23]:
mediana=df['product_price'].median()
mediana

113.87

In [24]:
df['product_original_price']=df['product_original_price'].str.replace('[^0-9.]','',regex=True).astype(float)

In [25]:
df=df.drop(columns=['currency'])

In [27]:
mm=df['product_star_rating'].mean()
mm

np.float64(4.084294871794872)

In [28]:
df['product_star_rating']=df['product_star_rating'].fillna(df['product_star_rating'].mean())

In [29]:
df['product_minimum_offer_price']=df['product_minimum_offer_price'].str.replace('[^0-9.]','',regex=True).astype(float)

In [30]:
df['product_minimum_offer_price']=df['product_minimum_offer_price'].fillna(df['product_minimum_offer_price'].median())

In [35]:
df['sales_volume']

0       4K+ bought in past month
1       1K+ bought in past month
2       2K+ bought in past month
3      500+ bought in past month
4      500+ bought in past month
                 ...
335                          NaN
336     50+ bought in past month
337                          NaN
338    300+ bought in past month
339     3K+ bought in past month
Name: sales_volume, Length: 315, dtype: object

In [32]:
df=df.drop(columns=['delivery'])

In [33]:
extracted = df["sales_volume"].str.extract(r"(\d+)\s*([kK])?")

In [34]:
df["sales_volume_clean"] = extracted[0].astype(float)

In [36]:
df.loc[extracted[1].notna(), "sales_volume_clean"] *= 1000

In [38]:
df['has_discounts']=df['product_original_price'].notna()

In [42]:
df['product_original_price']=df['product_original_price'].fillna(df['product_price'])

In [43]:
df

,asin,product_title,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,has_variations,sales_volume_clean,has_discounts
0,B0BQ118F2T,moto g play 2023 3-day battery unlocked made f...,99.00,169.99,4.0,1319,16,69.88,False,False,True,False,4K+ bought in past month,False,4000.0,True
1,B0CV2W1TKZ,"samsung galaxy a15 (sm-155m/dsn), 128gb 6gb ra...",153.99,153.99,4.2,186,4,147.50,False,False,True,False,1K+ bought in past month,False,1000.0,False
2,B09SM24S8C,"samsung galaxy a03s cell phone, at&amp;t gsm u...",69.00,99.99,3.8,597,35,64.99,False,False,True,False,2K+ bought in past month,True,2000.0,True
3,B0CHH1N9VY,tracfone | motorola moto g pure | locked | 32g...,49.99,49.99,4.2,2814,3,43.99,False,False,True,False,500+ bought in past month,False,500.0,False
4,B09T3MQSVP,"samsung galaxy a13 5g cell phone, at&amp;t gsm...",88.09,98.27,3.8,1338,31,70.40,False,False,True,False,500+ bought in past month,False,500.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"gimbal stabilizer for smartphone, 3-axis phone...",99.99,99.99,4.7,8,1,99.99,False,False,True,False,NaN,False,NaN,False
336,B0CHB24KQJ,[true military-grade] car phone holder【2024 st...,39.99,45.99,4.4,2589,1,39.99,False,False,True,False,50+ bought in past month,False,50.0,True
337,B01LXOPZ4W,wall mount cell phone charging shelf | multi-d...,273.00,273.00,4.1,45,1,273.00,False,False,False,False,NaN,False,NaN,False
338,B0CXPJK7F7,"sensyne 92&quot; cell phone tripod, selfie sti...",29.99,29.99,4.6,29066,1,29.99,True,False,True,False,300+ bought in past month,False,300.0,False
339,B0CQ237PFS,portable charger 33800mah usb c power bank wit...,45.95,69.95,4.4,672,1,45.95,False,False,True,False,3K+ bought in past month,False,3000.0,True

In [46]:
df['discount_value']=df['product_original_price']-df['product_price']

In [47]:
df

,asin,product_title,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,has_variations,sales_volume_clean,has_discounts,discount_value
0,B0BQ118F2T,moto g play 2023 3-day battery unlocked made f...,99.00,169.99,4.0,1319,16,69.88,False,False,True,False,4K+ bought in past month,False,4000.0,True,70.99
1,B0CV2W1TKZ,"samsung galaxy a15 (sm-155m/dsn), 128gb 6gb ra...",153.99,153.99,4.2,186,4,147.50,False,False,True,False,1K+ bought in past month,False,1000.0,False,0.00
2,B09SM24S8C,"samsung galaxy a03s cell phone, at&amp;t gsm u...",69.00,99.99,3.8,597,35,64.99,False,False,True,False,2K+ bought in past month,True,2000.0,True,30.99
3,B0CHH1N9VY,tracfone | motorola moto g pure | locked | 32g...,49.99,49.99,4.2,2814,3,43.99,False,False,True,False,500+ bought in past month,False,500.0,False,0.00
4,B09T3MQSVP,"samsung galaxy a13 5g cell phone, at&amp;t gsm...",88.09,98.27,3.8,1338,31,70.40,False,False,True,False,500+ bought in past month,False,500.0,True,10.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"gimbal stabilizer for smartphone, 3-axis phone...",99.99,99.99,4.7,8,1,99.99,False,False,True,False,NaN,False,NaN,False,0.00
336,B0CHB24KQJ,[true military-grade] car phone holder【2024 st...,39.99,45.99,4.4,2589,1,39.99,False,False,True,False,50+ bought in past month,False,50.0,True,6.00
337,B01LXOPZ4W,wall mount cell phone charging shelf | multi-d...,273.00,273.00,4.1,45,1,273.00,False,False,False,False,NaN,False,NaN,False,0.00
338,B0CXPJK7F7,"sensyne 92&quot; cell phone tripod, selfie sti...",29.99,29.99,4.6,29066,1,29.99,True,False,True,False,300+ bought in past month,False,300.0,False,0.00
339,B0CQ237PFS,portable charger 33800mah usb c power bank wit...,45.95,69.95,4.4,672,1,45.95,False,False,True,False,3K+ bought in past month,False,3000.0,True,24.00

In [51]:
df.to_csv("phone_search_cleaned.csv", index=False)